export const GET_ALL_MOVIES_REQUEST = "GET_ALL_MOVIES_REQUEST";
export const GET_ALL_MOVIES_SUCCESS = "GET_ALL_MOVIES_SUCCESS";
export const GET_ALL_MOVIES_FAILURE = "GET_ALL_MOVIES_FAILURE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
